Better UI for searchable selects
LedgerHQ/ledger-live-desktop pull request #3124
Opened 2020-08-17 14:15 UTC by juan-cortes

This is the result of a proposal the @bscholving made regarding searchable selectors in the app, it should be plug and play and not break any existing selectors. Basically if it's searchable and the list is displayed we change the UI to look like on the screenshots. If not, we keep it as is.

![image](https://user-images.githubusercontent.com/4631227/90406011-dc176300-e0a4-11ea-8f6f-3e27afa6998f.png)
![image](https://user-images.githubusercontent.com/4631227/90405922-bdb16780-e0a4-11ea-813b-11af4d6f92e0.png)
![image](https://user-images.githubusercontent.com/4631227/90406038-e3d70780-e0a4-11ea-943c-737e446bfba1.png)
![image](https://user-images.githubusercontent.com/4631227/90405950-c5710c00-e0a4-11ea-93e6-400958940f2b.png)
![image](https://user-images.githubusercontent.com/4631227/90405973-cdc94700-e0a4-11ea-89f4-07b6de1a76ff.png)

### Type

UI Polish

### Context

Slack conversation

### Parts of the app affected / Test plan

Any flow that has a selector, check it didn't break.

2020-08-19 12:24 UTC, Arnaud97234 requested changes
### Bug found
Add account: When the drop down list is displayed the placeholder and the Search text are both displayed one hover the other.

![image](https://user-images.githubusercontent.com/13007150/90634039-67b8fd00-e227-11ea-82d8-25d03ac52128.png)

2020-08-25 08:29 UTC, juan-cortes commented
I'll fix it tomorrow, other selects look good on your end? @Arnaud97234

2020-08-26 14:45 UTC, juan-cortes commented
Current version should have the add accounts flow fixed @Arnaud97234

2020-09-01 13:12 UTC, Arnaud97234 approved these changes

2020-09-02 10:55 UTC, merged