rework UI for coin control
LedgerHQ/ledger-live-desktop pull request #3130
Opened 2020-08-21 14:57 UTC by valpinkman

### Type

UI Improvement

### Context

LL-1684

### Parts of the app affected / Test plan

Coin Control
![image](https://user-images.githubusercontent.com/671786/90905531-9d4d1a00-e3d0-11ea-8297-18211f74dc6e.png)
<img width="1136" alt="Screenshot 2020-08-21 at 16 19 34" src="https://user-images.githubusercontent.com/671786/90904279-5ad70d80-e3cf-11ea-9110-53436f3ea3fc.png">
![image](https://user-images.githubusercontent.com/671786/90906082-69262900-e3d1-11ea-882c-978aeb898440.png)

![image](https://user-images.githubusercontent.com/671786/90904330-6c201a00-e3cf-11ea-83b1-15d66e059cc0.png)

2020-08-24 08:35 UTC, dasilvarosa requested changes
Awesome work! Some minor remarks:

**Send step 2 (Amount)**
- [x] Change order of the toggles: RBF first.
- [ ] RBF enabled by default.
- [ ] Reword (add a comma): “Include coins from unconfirmed, replaceable transactions”
- [ ] Reword: "Allow speeding up the transaction later by increasing the network fees (Replace-By-Fee)"

**Select coins modal**
- [ ] Reword title: Select coins --> Coin control
- [ ] DOGE 10 —> 10 DOGE to be consistent with the new way of displaying units
- [ ] More spacing between CTA and support link
- [ ] Reword strategies: “Oldest coins first (FIFO)“, “Minimize fees (optimize size)“, “Minimize future fees (merge coins)” 
- [ ] Slight reword:  "You cannot select coins from unconfirmed, replaceable transactions."

2020-08-25 15:33 UTC, valpinkman commented
>  Implement not enough coins selected error case like in the design. Make sure it's stickied when scrolling down the list of inputs.
@dasilvarosa seen with Chris, we keep the same banner for now, as there will be a new task to update them.
- [x] sticky done
I believe if we want a new error text, we need to throw a new error type (this involves libcore I think)

2020-08-26 11:41 UTC, dasilvarosa approved these changes

2020-08-31 18:39 UTC, Arnaud97234 requested changes
### Bugs found

1) In the coin control modal -> Pending tx: "Pending" and "Replaceable" text should be in Red.

Actual
<img width="567" alt="actual" src="https://user-images.githubusercontent.com/13007150/91753182-d30bb300-ebc7-11ea-918d-b2debc8aff50.png">

Expected
<img width="567" alt="expected" src="https://user-images.githubusercontent.com/13007150/91753192-d606a380-ebc7-11ea-9c26-a253d52c8ac0.png">
___________
___________
2) UTXOs shouldn't be displayed twice

<img width="709" alt="Screenshot 2020-08-31 at 19 39 47" src="https://user-images.githubusercontent.com/13007150/91753395-22ea7a00-ebc8-11ea-8910-cc09d1e0dafa.png">
___________
___________

3) Maximum spendable should adapt when user turns OFF "Include coin from unconfirmed / replaceable tx" AND there are some UTXOs corresponding to RBF tx.
- if OFF -> Max spendable = Balance - Replaceable UTXOs

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13007150/91754556-e750af80-ebc9-11ea-9fa3-bd61dea375b9.gif)

2020-09-01 14:24 UTC, Arnaud97234 requested changes
In the coin control modal -> Pending tx: "Pending" and "Replaceable" text should be in Red.

Actual
<img width="567" alt="actual" src="https://user-images.githubusercontent.com/13007150/91753182-d30bb300-ebc7-11ea-918d-b2debc8aff50.png">

Expected
<img width="567" alt="expected" src="https://user-images.githubusercontent.com/13007150/91753192-d606a380-ebc7-11ea-9c26-a253d52c8ac0.png">

2020-09-01 17:44 UTC, Arnaud97234 submitted a review, later dismissed

2020-09-03 08:10 UTC, dasilvarosa approved these changes

2020-09-03 16:12 UTC, valpinkman commented on src/renderer/components/OperationsList/AddressCell.js
> +export const SplitAddress = ({ value }: { value: string }) => {
I changed this, reusing the same component.

2020-09-03 16:16 UTC, IAmMorrow submitted a review, later dismissed

2020-09-03 16:17 UTC, Arnaud97234 submitted a review, later dismissed

2020-09-04 09:41 UTC, Arnaud97234 approved these changes

2020-09-04 10:27 UTC, merged