UI rework Export to Mobile
LedgerHQ/ledger-live-desktop pull request #3138
Opened 2020-08-27 08:59 UTC by khalilbenihoud

I gave a bit of UI Polish to the **Export to mobile** feature.

I updated the:
- QR code size (I did a scan and worked perfectly with this size)
- No more scroll inside the modal
- We previsouly used the Send icon, I changed it to the QR code to match the one on Mobile.
- Updated some css and alignments.
- Updated some icons (Hide, Ban, Chevrons..)

<img width="254" alt="Screenshot 2020-08-27 at 10 57 26" src="https://user-images.githubusercontent.com/4894172/91419812-22fb1a80-e854-11ea-808c-fb8375f1214a.png">

<img width="1136" alt="Screenshot 2020-08-27 at 10 57 30" src="https://user-images.githubusercontent.com/4894172/91419912-3f975280-e854-11ea-9f4f-7f5d6ebc61a6.png">

2020-09-03 15:54 UTC, valpinkman commented on .vscode/settings.json
> +{
do not commit this file

2020-09-03 15:54 UTC, valpinkman commented on src/renderer/icons/Ban.js
> +      fill-rule="evenodd"
fillRule

2020-09-03 15:56 UTC, valpinkman requested changes
needs to be rebased also

2020-09-03 15:56 UTC, valpinkman commented on src/renderer/icons/Ban.js
> +      clip-rule="evenodd"
clipRule

2020-09-03 15:56 UTC, valpinkman commented on src/renderer/icons/Atom.js
> +    <path
those were exported to `const path` for performance

2020-09-03 15:56 UTC, valpinkman commented on src/renderer/screens/accounts/OptionsButton.js
>  import IconSend from "~/renderer/icons/Send";
remove unused import

2021-01-07 16:14 UTC, gre commented
```diff
diff --git a/.vscode/settings.json b/.vscode/settings.json
new file mode 100644
index 000000000..3b6641073
--- /dev/null
+++ b/.vscode/settings.json
@@ -0,0 +1,3 @@
+{
+    "git.ignoreLimitWarning": true
+}
\ No newline at end of file
diff --git a/src/renderer/components/AssetDistribution/Row.js b/src/renderer/components/AssetDistribution/Row.js
index 4ba56e3c5..cf0ec11d2 100644
--- a/src/renderer/components/AssetDistribution/Row.js
+++ b/src/renderer/components/AssetDistribution/Row.js
@@ -118,7 +118,7 @@ const Row = ({ item: { currency, amount, distribution }, isVisible }: Props) =>
       <Distribution>
         {!!distribution && (
           <>
-            <Text ff="Inter" color="palette.text.shade100" fontSize={3}>
+            <Text ff="Inter|Medium" color="palette.text.shade100" fontSize={3}>
               {`${percentage}%`}
             </Text>
             <Bar progress={isVisible ? percentage : "0"} progressColor={color} />
diff --git a/src/renderer/components/Exporter/ExportInstructions.js b/src/renderer/components/Exporter/ExportInstructions.js
index 743d66b34..2009f9de6 100644
--- a/src/renderer/components/Exporter/ExportInstructions.js
+++ b/src/renderer/components/Exporter/ExportInstructions.js
@@ -7,13 +7,13 @@ import Text from "~/renderer/components/Text";
 import BulletRow from "~/renderer/components/BulletRow";

 const BulletRowIcon = styled(Box).attrs(() => ({
-  ff: "Inter|Regular",
+  ff: "Inter|SemiBold",
   fontSize: 10,
   textAlign: "center",
   color: "wallet",
   pl: 2,
 }))`
-  background-color: rgba(100, 144, 241, 0.2);
+  background-color: ${p => p.theme.colors.blueTransparentBackground};
   border-radius: 12px;
   display: inline-flex;
   height: 18px;
@@ -30,10 +30,10 @@ const Plus = styled(Box).attrs(() => ({
   pl: 2,
 }))`
   display: inline-flex;
-  background-color: rgba(100, 144, 241, 0.2);
+  background-color: ${p => p.theme.colors.blueTransparentBackground};
   border-radius: 4px;
   height: 14px;
-  line-height: 14px;
+  line-height: 12px;
   width: 14px;
   padding: 0;
 `;
@@ -90,12 +90,12 @@ const stepsImportMobile = [

 const ExportInstructions = () => (
   <>
-    <Box shrink style={{ width: 330, fontSize: 13, marginTop: 20 }}>
+    <Box shrink style={{ fontSize: 13, margin: 15 }}>
       <Text ff="Inter|SemiBold" color="palette.text.shade100">
         <Trans i18nKey="settings.export.modal.listTitle" />
       </Text>
     </Box>
-    <Box style={{ width: 330 }}>
+    <Box>
       {stepsImportMobile.map(step => (
         <BulletRow key={step.key} step={step} />
       ))}
diff --git a/src/renderer/components/Exporter/index.js b/src/renderer/components/Exporter/index.js
index e1f255b4c..2d1b83c84 100644
--- a/src/renderer/components/Exporter/index.js
+++ b/src/renderer/components/Exporter/index.js
@@ -17,7 +17,7 @@ type Props = OwnProps & {
 const Exporter = ({ accounts }: Props) => (
   <Box justifyContent="center" alignItems="center">
     <Box flow={2}>
-      <QRCodeExporter accounts={accounts} size={330} />
+      <QRCodeExporter accounts={accounts} size={208} />
     </Box>
     <ExportInstructions />
   </Box>
diff --git a/src/renderer/components/Price.js b/src/renderer/components/Price.js
index 00650a6b0..39e0bf031 100644
--- a/src/renderer/components/Price.js
+++ b/src/renderer/components/Price.js
@@ -41,7 +41,7 @@ type Props = OwnProps & {
 };

 const PriceWrapper = styled(Box).attrs(() => ({
-  ff: "Inter",
+  ff: "Inter|Medium",
   horizontal: true,
 }))`
   line-height: 1.2;
diff --git a/src/renderer/icons/AngleDown.js b/src/renderer/icons/AngleDown.js
index 794aa29ea..684d02a12 100644
--- a/src/renderer/icons/AngleDown.js
+++ b/src/renderer/icons/AngleDown.js
@@ -3,10 +3,10 @@
 import React from "react";

 const AngleDown = ({ size, color = "currentColor" }: { size: number, color?: string }) => (
-  <svg viewBox="0 0 16 14" height={size} width={size * 0.875}>
+  <svg viewBox="0 0 16 16" height={size} width={size * 0.875}>
     <path
       fill={color}
-      d="M7.70123023 10.2169906L3.62390158 6.53574061c-.16520211-.146875-.16520211-.384375 0-.53125l.24956063-.221875c.16520211-.146875.43233744-.146875.59753955 0L8 8.97949061l3.5289982-3.19375c.1652022-.146875.4323375-.146875.5975396 0l.2495606.221875c.1652021.146875.1652021.384375 0 .53125L8.29876977 10.2201156c-.16520211.14375-.43233743.14375-.59753954-.003125z"
+      d="M7.71875 10.875C7.875 11.0312 8.09375 11.0312 8.25 10.875L12.875 6.28125C13.0312 6.15625 13.0312 5.90625 12.875 5.75L12.25 5.15625C12.125 5 11.875 5 11.7188 5.15625L8 8.84375L4.25 5.15625C4.09375 5 3.875 5 3.71875 5.15625L3.09375 5.75C2.9375 5.90625 2.9375 6.15625 3.09375 6.28125L7.71875 10.875Z"
     />
   </svg>
 );
diff --git a/src/renderer/icons/AngleUp.js b/src/renderer/icons/AngleUp.js
index ff2381495..631bb6169 100644
--- a/src/renderer/icons/AngleUp.js
+++ b/src/renderer/icons/AngleUp.js
@@ -2,16 +2,12 @@

 import React from "react";

-const path = (
-  <path
-    fill="currentColor"
-    d="M10.345 6.414l6.012 5.734c.19.184.19.48 0 .665l-.804.773a.502.502 0 0 1-.69 0L10 8.957l-4.862 4.629a.502.502 0 0 1-.69 0l-.805-.774a.457.457 0 0 1 0-.664l6.012-5.734c.19-.184.5-.184.69 0z"
-  />
-);
-
-const AngleUp = ({ size }: { size: number }) => (
-  <svg viewBox="0 0 20 20" height={size} width={size * 0.875}>
-    {path}
+const AngleUp = ({ size, color = "currentColor" }: { size: number, color?: string }) => (
+  <svg viewBox="0 0 16 16" height={size} width={size * 0.875}>
+    <path
+      fill={color}
+      d="M8.25 5.15625C8.09375 5 7.875 5 7.71875 5.15625L3.09375 9.71875C2.9375 9.875 2.9375 10.125 3.09375 10.25L3.71875 10.875C3.875 11.0312 4.09375 11.0312 4.25 10.875L8 7.1875L11.7188 10.875C11.875 11.0312 12.125 11.0312 12.25 10.875L12.875 10.25C13.0312 10.125 13.0312 9.875 12.875 9.71875L8.25 5.15625Z"
+    />
   </svg>
 );

diff --git a/src/renderer/icons/Atom.js b/src/renderer/icons/Atom.js
index 62fd4b88f..39e1e5a47 100644
--- a/src/renderer/icons/Atom.js
+++ b/src/renderer/icons/Atom.js
@@ -2,16 +2,12 @@

 import React from "react";

-const path = (
-  <path
-    fill="currentColor"
-    d="M15.246.803c-.954-.95-2.618-1.02-4.695-.195-.827.33-1.689.81-2.551 1.375C7.138 1.418 6.276.938 5.449.608 3.377-.217 1.71-.15.754.803-.615 2.166-.058 5.007 1.926 8.018-.058 11.028-.615 13.87.754 15.233c.513.51 1.231.767 2.108.767.754 0 1.627-.19 2.587-.572.827-.33 1.689-.81 2.551-1.375.862.565 1.724 1.045 2.551 1.375.96.382 1.832.572 2.588.572.876 0 1.594-.256 2.107-.767 1.369-1.363.812-4.204-1.172-7.215 1.984-3.01 2.541-5.852 1.172-7.215zm-4.268.864c1.597-.636 2.857-.656 3.459-.058.82.816.46 2.934-1.07 5.401a22.166 22.166 0 0 0-2.03-2.315A22.114 22.114 0 0 0 9.01 2.697c.667-.411 1.33-.776 1.969-1.03zm-9.414-.058c.291-.29.737-.434 1.3-.434.601 0 1.335.164 2.159.492.638.254 1.301.618 1.969 1.03a22.186 22.186 0 0 0-2.329 1.998 22.166 22.166 0 0 0-2.03 2.315c-1.53-2.467-1.89-4.585-1.07-5.4zm3.458 12.76c-1.595.636-2.855.657-3.459.057-.82-.815-.46-2.933 1.07-5.4a22.166 22.166 0 0 0 2.03 2.314c.75.747 1.536 1.403 2.328 1.999-.667.411-1.33.776-1.969 1.03zm.45-3.835a20.63 20.63 0 0 1-2.157-2.516A20.87 20.87 0 0 1 8 3.36a20.897 20.897 0 0 1 4.685 4.658A20.87 20.87 0 0 1 8 12.676a20.93 20.93 0 0 1-2.527-2.142zm8.964 3.892c-.602.6-1.862.58-3.459-.057-.638-.254-1.301-.619-1.969-1.03a22.186 22.186 0 0 0 2.329-1.999 22.166 22.166 0 0 0 2.03-2.315c1.53 2.468 1.89 4.586 1.07 5.401zM8 6.022a2.002 2.002 0 0 0-2.005 1.996c0 1.1.9 1.995 2.005 1.995a2.002 2.002 0 0 0 2.005-1.995c0-1.1-.9-1.996-2.005-1.996zm0 2.851a.857.857 0 0 1-.859-.855c0-.473.385-.855.859-.855.475 0 .859.382.859.855A.857.857 0 0 1 8 8.873z"
-  />
-);
-
 const Atom = ({ size }: { size: number }) => (
   <svg viewBox="0 0 16 16" height={size} width={size}>
-    {path}
+    <path
+      fill="currentColor"
+      d="M13.4062 8C15.0938 5.40625 15.5 2.96875 14.25 1.75C13.0312 0.5 10.5938 0.90625 8 2.59375C5.375 0.90625 2.9375 0.5 1.71875 1.75C0.46875 2.96875 0.875 5.40625 2.5625 8C0.875 10.625 0.46875 13.0625 1.71875  [...]

2021-01-07 16:15 UTC, gre commented
This PR was outdated and the branch is too old to be kept on **upstream** (it never should have been on upstream in first place)

I kept above a save of the diff that this PR was doing.

2021-01-07 16:15 UTC, closed without merging