add xpub warning on advanced account settings (bitcoin family)
LedgerHQ/ledger-live-desktop pull request #3151
Opened 2020-09-02 15:06 UTC by valpinkman

Adds and info banner into Account => Settings => Advanced warning about the xpub use. 

Only for Bitcoin family

### Type

Feat

### Context

LL-2039

2020-09-02 16:15 UTC, Arnaud97234 submitted a review, later dismissed

2020-09-04 11:37 UTC, juan-cortes requested changes

2020-09-04 11:37 UTC, juan-cortes commented on src/renderer/modals/SettingsAccount/AccountSettingRenderBody.js
> +    console.log({ account });
Remove, right?

2020-09-04 11:52 UTC, juan-cortes commented on src/renderer/modals/SettingsAccount/AccountSettingRenderBody.js
> +    console.log({ account });
```suggestion
```

2020-09-04 13:22 UTC, merged