Ll 3391
LedgerHQ/ledger-live-desktop pull request #3257
Opened 2020-10-26 16:04 UTC by machard

Websocket Bridge

<img width="518" alt="Capture d’écran 2020-10-26 à 17 02 07" src="https://user-images.githubusercontent.com/5071029/97196859-3a4f7900-17ad-11eb-9d12-ed235100bb10.png">
<img width="559" alt="Capture d’écran 2020-10-26 à 17 02 32" src="https://user-images.githubusercontent.com/5071029/97196863-3c193c80-17ad-11eb-8e7a-a28d31270bf8.png">
<img width="538" alt="Capture d’écran 2020-10-26 à 17 03 20" src="https://user-images.githubusercontent.com/5071029/97196864-3cb1d300-17ad-11eb-8b9f-003414f31d10.png">
<img width="539" alt="Capture d’écran 2020-10-26 à 17 03 31" src="https://user-images.githubusercontent.com/5071029/97196866-3d4a6980-17ad-11eb-9d8e-34483b1028eb.png">
<img width="586" alt="Capture d’écran 2020-10-26 à 17 03 36" src="https://user-images.githubusercontent.com/5071029/97196869-3de30000-17ad-11eb-80e6-438d5255b3f8.png">

### Type

Feature

### Context

https://ledgerhq.atlassian.net/browse/LL-3391

### Parts of the app affected / Test plan

in dev mode, go to experimental settings (last line)
on a build, use https://ledger-live-tools.now.sh/bridgetest

2020-10-29 13:23 UTC, gre submitted a review, later dismissed

2020-10-29 13:31 UTC, nabil-brn requested changes
Please make the modal component persistent, it'll be better that clicking outside of the element will not deactivate it.

![](https://user-images.githubusercontent.com/16896559/97579757-bdaddc00-19f2-11eb-91c6-c817936c1e44.png)

---
99d3559b (HEAD, machard/LL-3391) add more padding

2020-10-30 09:55 UTC, nabil-brn requested changes
✓ QA-ed

---
149a8f32 (HEAD -> LL-3391, machard/LL-3391) Merge branch 'LL-3391' of github.com:machard/ledger-live-desktop into LL-3391

2020-10-30 10:26 UTC, nabil-brn approved these changes
✓ QA-ed

---
149a8f32 (HEAD -> LL-3391, machard/LL-3391) Merge branch 'LL-3391' of github.com:machard/ledger-live-desktop into LL-3391

2020-10-30 12:54 UTC, merged