compound fixes
LedgerHQ/ledger-live-desktop pull request #3258
Opened 2020-10-27 17:23 UTC by valpinkman

2020-11-02 13:17 UTC, gre approved these changes

2020-11-03 15:24 UTC, valpinkman commented
@Arnaud97234 @nabil-brn 

For the Fixes
https://ledgerhq.atlassian.net/browse/LL-3808
https://ledgerhq.atlassian.net/browse/LL-3673

2020-11-04 18:15 UTC, Arnaud97234 requested changes
I can still reproduce https://ledgerhq.atlassian.net/browse/LL-3808

2020-11-05 14:06 UTC, gre commented
agreed with Arnaud, we'll merge all this work and continue forward on fixing what was found in another PR.

2020-11-05 14:06 UTC, merged