LL-3816 (Analytics) add source for tracking page events
LedgerHQ/ledger-live-desktop pull request #3270
Opened 2020-11-03 08:52 UTC by LFBarreto

(Analytics): add optional source property from navigation routing to all track page events

All tracking page events can now send an optional source property.
This should happen everywhere we have an UI triggering a routing update since all history.push have been updated with that extra param.

### Type

Analytics
### Context

LL-3816
### Parts of the app affected / Test plan

Using the console test out navigation from sidebar you should see the `source: "sidebar"` property on the event. same for other navigation.

2020-11-03 08:56 UTC, gre commented
HODL for discussion in LL. especially around the fact using the buttons event should be enough to identify user's behavior.

2020-11-10 20:55 UTC, gre submitted a review, later dismissed

2020-11-12 17:45 UTC, Arnaud97234 reviewed
From sidebar:
- [x] Portfolio
- [x] Accounts
- [x] Buy
- [x] Swap
- [x] Compound
- [x] Manager
- [x] Experimental Feature

From asset allocation:
- [x] Portfolio asset allocation
- [x] Account

From accounts page:
- [x] Account
- [x] subAccount

From account page:
- [x] SubAccount
- [x] Buy
- [x] Swap

From breadcrumb:
- [x] Portfolio
- [x] Accounts
- [x] Account
- [x] SubAccount

From operation details:
- [x] Account
- [x] subAccount

From topBar:
- [x] Settings

2020-11-12 18:06 UTC, Arnaud97234 requested changes
- Can't access to manager from add account modal (if app missing on the device)
- No event when accessing to Settings from Experimental flag in the sidebar

2020-11-16 10:43 UTC, Arnaud97234 approved these changes

2020-11-16 13:18 UTC, merged