LL-3900 if no device currently use lastDeviceSeen in events context
LedgerHQ/ledger-live-desktop pull request #3334
Opened 2020-11-27 15:08 UTC by machard

https://ledgerhq.atlassian.net/browse/LL-3900

2020-11-30 19:33 UTC, gre requested changes

2020-11-30 19:33 UTC, gre commented on src/renderer/analytics/segment.js
>    const deviceInfo = device ? { modelId: device.modelId } : {};
I see two issues in that:

- getCurrentDevice returns a Device but lastSeenDeviceSelector returns a DeviceModelInfo
- it doesn't solve LL-3900: we want to add in the "deviceInfo" object that I think comes from DeviceModelInfo

My proposal is to actually drop the "getCurrentDevice" usage. in the lastSeenDeviceSelector, we have enough we need and we can just use that. 

https://github.com/LedgerHQ/ledger-live-common/blob/5fd037de618d245e960046e69aab240c847cc7d2/src/types/manager.js#L31-L35

i would suggest that we track `{ modelId, deviceVersion, appLength }` (deviceVersion is deviceInfo.version, appLength is apps.length )

kinda consistently with https://github.com/LedgerHQ/ledger-live-desktop/blob/develop/src/renderer/screens/manager/Dashboard.js#L73-L76

2020-12-03 09:10 UTC, gre submitted a review, later dismissed

2020-12-07 15:51 UTC, Arnaud97234 approved these changes

2020-12-07 17:25 UTC, merged