LL-2846 add warning box when utxo > 50
LedgerHQ/ledger-live-desktop pull request #3341
Opened 2020-11-30 08:39 UTC by machard

https://ledgerhq.atlassian.net/browse/LL-2846

2020-11-30 19:25 UTC, gre requested changes

2020-11-30 19:25 UTC, gre commented on src/renderer/modals/Send/steps/StepSummary.js
> +    const utxoLag = mainAccount.operationsCount >= 50;
we should warn when the transaction uses a lot of utxo. not when the accounts have a lot of utxos.

TransactionStatus have a txInputs array. that you can use.

probably `status.txInputs ? status.txInputs.length >= WARN_FROM_UTXO_COUNT : false`

the tx will be slow where there are a lot of utxo inputs to create the transaction.

(also, it is good if you can make this a variable)

2020-12-01 18:40 UTC, gre submitted a review, later dismissed

2020-12-02 21:17 UTC, Arnaud97234 approved these changes

2020-12-02 22:13 UTC, merged