add swap infos in the validate on device screen
LedgerHQ/ledger-live-desktop pull request #3359
Opened 2020-12-03 14:04 UTC by machard

https://ledgerhq.atlassian.net/browse/LL-3572

2020-12-09 22:16 UTC, gre requested changes

2020-12-09 22:16 UTC, gre commented on src/renderer/components/DeviceAction/rendering.js
> +import _ from "lodash";
Usually we don't import _ but we will import the fn style (e.g. leash/map)

2020-12-09 22:16 UTC, gre commented on src/renderer/modals/Swap/SwapBody.js
> +  transaction: Transaction, // FIXME
I guess this makes it no longer a FIXME

2020-12-11 19:03 UTC, gre submitted a review, later dismissed

2020-12-16 17:06 UTC, valpinkman submitted a review, later dismissed

2020-12-23 11:58 UTC, Arnaud97234 requested changes
Typo is incorrect (too big):

Actual:
![image](https://user-images.githubusercontent.com/13007150/102994001-80f7f000-451e-11eb-8cb7-51e219b2716c.png)

Expected:
![image](https://user-images.githubusercontent.com/13007150/102994021-88b79480-451e-11eb-9ecd-66356e838b65.png)

2020-12-23 12:05 UTC, cthepot-ledger commented
@machard the font isnot the same on the second screen. Kindly amend for consistency 
<img width="508" alt="Screenshot 2020-12-23 at 13 04 48" src="https://user-images.githubusercontent.com/23069507/102994541-8c97e680-451f-11eb-9620-27ed482251b6.png">

<img width="506" alt="Screenshot 2020-12-23 at 13 04 32" src="https://user-images.githubusercontent.com/23069507/102994536-8a358c80-451f-11eb-8525-68ed6c3f864e.png">

2020-12-23 15:47 UTC, Arnaud97234 approved these changes

2020-12-29 11:15 UTC, valpinkman approved these changes

2020-12-29 11:16 UTC, merged