various onboarding fixed
LedgerHQ/ledger-live-desktop pull request #3399
Opened 2020-12-18 16:13 UTC by IAmMorrow

fixed device specific wording
added link to recovery phrase help
last question of the quizz now show "finish" button

2020-12-18 17:02 UTC, machard commented
You will update the first screen illustration as well?

2020-12-18 17:26 UTC, cthepot-ledger commented
- 4185 requires bold font inside drawer on "never" and "always"
- 4177 is done
- 4181 is done
- 4127 is done

@IAmMorrow

2020-12-18 17:30 UTC, cthepot-ledger commented
can we process 4247 at the same time please

2020-12-21 15:47 UTC, valpinkman commented
Fixed LL-4247 as well

![image](https://user-images.githubusercontent.com/671786/102794781-25a5f080-43ac-11eb-8d6d-9a0a1bca63dd.png)

2020-12-21 17:02 UTC, juan-cortes requested changes

2020-12-22 11:37 UTC, juan-cortes commented on src/renderer/components/Onboarding/Screens/SelectDevice/devices.js
> +const devices = {
To me, this design change means we should reflect this "shorthand" product name in live-common.
For now we can have it locally, but maybe worth taking a look when @gre is back

2020-12-22 11:37 UTC, juan-cortes submitted a review, later dismissed
lgtm

2020-12-23 09:44 UTC, machard commented
can you update the snapshot ?

2020-12-24 10:42 UTC, valpinkman requested changes

2020-12-24 10:42 UTC, valpinkman commented on src/renderer/components/Onboarding/Help/RecoverySeed.js
> +        <FakeLink onClick={() => openURL(urls.whatIsARecoveryPhrase)}>
inside useCallback

2020-12-24 10:42 UTC, valpinkman commented on src/renderer/modals/Terms/index.js
> +                      <Text onClick={() => openURL(urls.terms)} color="wallet" />
inside useCallback

2020-12-24 10:42 UTC, valpinkman commented on src/renderer/modals/Terms/index.js
> +                      <Text onClick={() => openURL(urls.privacyPolicy)} color="wallet" />
inside useCallback

2021-01-04 08:00 UTC, gre commented
CI to check

2021-01-08 15:49 UTC, machard commented
@IAmMorrow I think onboarding test fail because #modal-terms-checkbox-loss is gone and firmware should pass when you rerun, its an issue most likely due to a slow be

2021-01-13 11:50 UTC, Arnaud97234 requested changes
On onboarding -> Genuine check Success screen the device model should be be corresponding to the device selected at the beginning of the Onboarding. It's always "Your Ledger Nano X is genuine ..." even when selecting a Blue or a NanoS.
![Screenshot 2021-01-13 at 12 38 45](https://user-images.githubusercontent.com/13007150/104448743-d9f6f900-559d-11eb-9c5a-d7c886daf8a8.png)

2021-01-13 14:51 UTC, Arnaud97234 submitted a review, later dismissed

2021-01-13 19:29 UTC, gre commented
@Arnaud97234  is this mergeable? I'm confused by the :x: and then ✅

2021-01-15 08:37 UTC, nabil-brn requested changes
![image](https://user-images.githubusercontent.com/16896559/104700893-231d8900-5715-11eb-8f91-f277730880f7.png)

It's missing spaces before and after device icons.
---
2.20.0-sha.ad97b5a17864f73614b430a7101ad5ca69942d79-win.exe.zip

2021-01-15 08:40 UTC, nabil-brn commented
![image](https://user-images.githubusercontent.com/16896559/104701605-84ddf300-5715-11eb-824a-d834dd1d7274.png)

Last answer is overlapping the illustration.

---
2.20.0-sha.ad97b5a17864f73614b430a7101ad5ca69942d79-win.exe.zip

2021-01-15 08:46 UTC, gre commented
@IAmMorrow can you check? thanks

2021-01-22 08:41 UTC, machard commented
<img width="956" alt="Capture d’écran 2021-01-22 à 09 40 41" src="https://user-images.githubusercontent.com/5071029/105467398-f0840b00-5c95-11eb-8a04-f2fe06f3ebd2.png">

Some ids have been removed that are necessary for the onboarding test flow

2021-01-26 13:18 UTC, valpinkman approved these changes

2021-01-26 14:51 UTC, nabil-brn requested changes
https://github.com/LedgerHQ/ledger-live-desktop/pull/3399#pullrequestreview-569056818

2021-01-26 15:39 UTC, gre commented
enjoy your incoming screenshot reset :trollface:

2021-01-26 16:07 UTC, gre commented
:itshappening:

2021-01-26 18:53 UTC, gre approved these changes

2021-01-27 11:27 UTC, nabil-brn approved these changes
✓ QA-ed

---
2.20.0-sha.181927b52f5e6f10ff48864190e2e944d6698c2b-mac.dmg

2021-01-27 11:28 UTC, merged