This is a mashup PR that contains all the latest UI changes/fixes that have been done lately
LedgerHQ/ledger-live-desktop pull request #3425
Opened 2020-12-29 14:15 UTC by valpinkman

To make it easier to QA, all the previous PR have been reviewed by devs, and just need a QA pass

- https://github.com/LedgerHQ/ledger-live-desktop/pull/3387 => [LL-3914](https://ledgerhq.atlassian.net/browse/LL-3914)
- https://github.com/LedgerHQ/ledger-live-desktop/pull/3393 => [LL-3961](https://ledgerhq.atlassian.net/browse/LL-3961)
- https://github.com/LedgerHQ/ledger-live-desktop/pull/3402 => [LL-4170](https://ledgerhq.atlassian.net/browse/LL-4170)
- https://github.com/LedgerHQ/ledger-live-desktop/pull/3414 => [LL-4258](https://ledgerhq.atlassian.net/browse/LL-4258)
- https://github.com/LedgerHQ/ledger-live-desktop/pull/3416 => [LL-2803](https://ledgerhq.atlassian.net/browse/LL-2803)
- https://github.com/LedgerHQ/ledger-live-desktop/pull/3423 => [LL-4185](https://ledgerhq.atlassian.net/browse/LL-4185)
- https://github.com/LedgerHQ/ledger-live-desktop/pull/3424 => [LL-4261](https://ledgerhq.atlassian.net/browse/LL-4261)

### Type

Various UI Fixes

2020-12-30 09:42 UTC, machard commented on src/renderer/components/TabBar.js
> +          id={withId ? `settings-${tab.toLowerCase()}-tab` : ""}
i believe ids only work on native elements

2021-01-04 07:55 UTC, gre approved these changes

2021-01-05 11:44 UTC, nabil-brn requested changes
- [x] #3387 => LL-3914 -> no more present in algorand earn reward modal, only jar?
- [x] #3393 => LL-3961 -> navbar font is too big compared to figma
- [ ] #3402 => LL-4170 -> icons look stretched
- [x] #3414 => LL-4258
- [x] #3416 => LL-2803 
- [x] #3423 => LL-4185 -> "NEVER" is not in bold, and the second point of jira ticket is not fixed
- [ ] #3424 => LL-4261 -> from CTA (or not) when I've system theme (dark), the onboarding theme is dusk

---
06088200b (HEAD -> pr/valpinkman/3425, val/ui/mashup-pr) Update TabBar.js

2021-01-05 17:19 UTC, gre commented
you are close @valpinkman  =D

2021-01-06 16:12 UTC, nabil-brn requested changes
- [x]  #3387 => LL-3914
- [x]  #3424 => LL-4261
- [x]  #3402 => LL-4170
- [x]  #3414 => LL-4258
- [x]  #3416 => LL-2803
- [ ]  #3393 => LL-3961 -> Sub section font in settings are too small compared to figma
![image](https://user-images.githubusercontent.com/16896559/103790377-67d46080-5041-11eb-8738-f6106b468878.png)
- [ ]  #3423 => LL-4185
- NEVER / ALWAYS should be bold
![image](https://user-images.githubusercontent.com/16896559/103790991-31e3ac00-5042-11eb-94ea-0406a9edb546.png)
- PIN CODE step (icon should be a cross)
![image](https://user-images.githubusercontent.com/16896559/103790476-89cde300-5041-11eb-9f3e-59b662b8e735.png)

---
42e17cc03 (HEAD -> pr/valpinkman/3425) update algorand rewards ilustration

2021-01-07 13:15 UTC, nabil-brn requested changes
Icon is fixed but now I have a mix of languages. I though it was fixed on develop already ?
![image](https://user-images.githubusercontent.com/16896559/103896629-90686300-50f2-11eb-9ba6-bf417c2bdee9.png)

NEVER / ALWAYS should be in **bold**.
![image](https://user-images.githubusercontent.com/16896559/103896679-a1b16f80-50f2-11eb-9e18-a85094f7b542.png)

---
b848b4c0d (grafted, HEAD -> pr/valpinkman/3425, val/ui/mashup-pr) fix eslint

2021-01-07 16:00 UTC, nabil-brn submitted a review, later dismissed

2021-01-07 16:56 UTC, nabil-brn approved these changes

2021-01-07 17:08 UTC, merged