updated coinify buy api to v2
LedgerHQ/ledger-live-desktop pull request #3444
Opened 2021-01-05 17:55 UTC by IAmMorrow

This PR transition LLD from using the widget deprecated buy API to the new one (already used by sell mode).

To QA:
Simply initiate a buy transaction, choose to pay by card and confirm that the device receive address check works and takes the widget to the credit card info part of the flow. The rest is out of our scope.

2021-01-05 18:20 UTC, gre commented
^good bot

2021-01-05 18:20 UTC, gre submitted a review, later dismissed

2021-01-07 12:28 UTC, cthepot-ledger commented
QAed - GO on product side only

2021-01-11 02:08 UTC, nabil-brn requested changes
![image](https://user-images.githubusercontent.com/16896559/104142060-1d910d80-53ba-11eb-859e-6e8f16833bd1.png)

Slash separator is visible on the modal.
> /


```javascript
// src\renderer\components\Breadcrumb\common.js

export const Separator: ThemedComponent<{}> = styled.div`
  &::after {
    content: "/";
    font-size: 13px;
    color: ${p => p.theme.colors.palette.divider};
    padding: 0 15px;
  }
`;
```

---
cdf047a09 (grafted, HEAD -> LL-3983/migrate-coinify-api, hugo/LL-3983/migrate-coinify-api) updated coinify buy api to v2

2021-01-12 17:10 UTC, nabil-brn approved these changes

2021-01-13 19:40 UTC, gre approved these changes

2021-01-13 19:40 UTC, merged