LL-3232 hide tokens tests
LedgerHQ/ledger-live-desktop pull request #3488
Opened 2021-01-19 16:09 UTC by valpinkman

adds hide tokens feature test

### Type

Test

### Context

LL-3232

2021-01-20 10:46 UTC, juan-cortes requested changes
Sadly this will need to be rebased/merged/rerun since it contains all the small chevrons on the sidebar.
Merge and get the suggested ones I'd say @valpinkman

2021-01-21 13:25 UTC, gre approved these changes

2021-01-21 13:35 UTC, juan-cortes approved these changes
lgtm

2021-01-22 09:43 UTC, juan-cortes commented
CI does not agree :pls:

2021-01-25 13:52 UTC, closed without merging