LL-4372 (Stratis): eol warning banner added
LedgerHQ/ledger-live-desktop pull request #3491
Opened 2021-01-20 10:42 UTC by LFBarreto

(Stratis): eol warning banner added
### Type

### Context

LL-4372
### Parts of the app affected / Test plan

Apps with Stratis accounts should see the warning message

2021-01-20 10:48 UTC, juan-cortes submitted a review, later dismissed
"October 16th" or "16th of October" maybe?
cc @dasilvarosa

2021-01-20 13:28 UTC, dasilvarosa requested changes

2021-01-20 13:28 UTC, dasilvarosa commented on src/config/urls.js
> +      "https://support.ledger.com/hc/en-us/articles/115005175329-Stratis-STRAT-",
zendesk uses Canonical links, no need for the title at the end. You can use:
https://support.ledger.com/hc/en-us/articles/115005175329

2021-01-21 14:28 UTC, gre submitted a review, later dismissed

2021-01-21 17:42 UTC, nabil-brn submitted a review, later dismissed
✓ QA-ed

---
c7ed4ba8b (HEAD -> LL-4372, luiz/LL-4372) (Stratis): warning banner url updated

2021-01-23 08:08 UTC, gre commented
Conflicts

2021-01-26 12:14 UTC, gre approved these changes

2021-01-26 13:24 UTC, valpinkman approved these changes

2021-01-26 13:40 UTC, Arnaud97234 approved these changes

2021-01-26 13:55 UTC, dasilvarosa approved these changes

2021-01-26 13:57 UTC, merged