Live common 18.3.1
LedgerHQ/ledger-live-desktop pull request #3525
Opened 2021-01-28 11:07 UTC by gre

https://github.com/LedgerHQ/ledger-live-common/releases/tag/v18.3.1

closes #3516 
closes #3514 

includes some minor libs bump (impacts: confettis, tooltips)

2021-01-28 17:35 UTC, valpinkman approved these changes

2021-02-01 05:59 UTC, nabil-brn requested changes
- LL-4416 update ExchangeRateAmount errors https://github.com/LedgerHQ/ledger-live-desktop/pull/3512
There is no more amount.
![image](https://user-images.githubusercontent.com/16896559/106417332-1bb7e880-6454-11eb-8388-bb5c7ab65c50.png)
- LL-4442 add day in portfolio graph
I did a send at 06:34 am and it doesn't appear in the middle of the graph (I can't even mouseover the new point on the graph)
![image](https://user-images.githubusercontent.com/16896559/106420349-b6b3c100-645a-11eb-8f3b-3fd3653af96d.png)

---
2.20.0-sha.665ae30a9fbb8523cad173ce920440ed56b1c187-win.exe.zip

2021-02-01 07:56 UTC, gre commented
@nabil-brn 

- 1D is disabled (not for this bump, like on mobile it was actually not there)
- translation for ExchangeRateAmount is fixed.

2021-02-02 09:22 UTC, valpinkman approved these changes

2021-02-02 09:52 UTC, nabil-brn approved these changes

2021-02-02 09:52 UTC, merged