Added information center and announcement panel
LedgerHQ/ledger-live-desktop pull request #3587
Opened 2021-02-18 17:57 UTC by IAmMorrow

2021-03-23 16:44 UTC, valpinkman requested changes

2021-03-23 16:44 UTC, valpinkman commented on src/renderer/components/AnnouncementProviderWrapper.js
> +  const [startDate] = useState(new Date());
I think `useMemo` is better here as you don't need a setter apparently

2021-03-23 16:44 UTC, valpinkman commented on src/renderer/components/ToastOverlay/TimeBasedProgressBar.js
> +            ...props,
not sure you want props at the end ? are you sure it will not override any properties you've set right before ?

2021-03-23 16:44 UTC, valpinkman commented on src/renderer/components/TopBar/NotificationIndicator/index.js
> +        onRequestClose={() => dispatch(closeInformationCenter())}
`useCallback` here

2021-03-23 16:44 UTC, valpinkman commented on src/renderer/components/TopBar/NotificationIndicator/index.js
> +            dispatch(openInformationCenter());
same here

2021-03-24 08:46 UTC, valpinkman requested changes

2021-03-24 08:46 UTC, valpinkman commented on src/renderer/components/TopBar/NotificationIndicator/AnnouncementPanel.js
> +        {moment(date).format("MMMM, Do, YYYY")}
wrap this in a memo'd component

2021-03-24 12:52 UTC, Arnaud97234 approved these changes

2021-03-24 13:18 UTC, valpinkman submitted a review, later dismissed

2021-03-24 18:47 UTC, gre commented
@IAmMorrow please merge develop to solve conflicts. thx

2021-03-25 10:09 UTC, valpinkman submitted a review, later dismissed

2021-03-25 11:01 UTC, Arnaud97234 submitted a review, later dismissed

2021-03-25 12:31 UTC, LFBarreto submitted a review, later dismissed

2021-03-25 17:48 UTC, Arnaud97234 approved these changes

2021-03-25 18:02 UTC, merged