LL-4431 (Onboarding): lang switcher activated
LedgerHQ/ledger-live-desktop pull request #3591
Opened 2021-02-19 13:50 UTC by LFBarreto

(Onboarding): activate lang switcher + fix on typo for terms localized
### Type

Feature
### Context

LL-4431
### Parts of the app affected / Test plan

Onboarding lang selector and terms localized

2021-03-05 14:40 UTC, valpinkman submitted a review, later dismissed

2021-03-08 19:02 UTC, Arnaud97234 commented
@LFBarreto @cthepot-ledger this part should be translated ?

2021-03-09 12:08 UTC, Arnaud97234 requested changes
Some UI bugs:
https://ledgerhq.atlassian.net/browse/LL-4431

2021-03-10 14:26 UTC, Arnaud97234 approved these changes

2021-03-11 08:12 UTC, merged