LL-4709 - no more oops
LedgerHQ/ledger-live-desktop pull request #3648
Opened 2021-03-09 12:58 UTC by machard

https://ledgerhq.atlassian.net/browse/LL-4709

2021-03-11 11:03 UTC, gre approved these changes

2021-03-21 15:37 UTC, nabil-brn requested changes

2021-03-21 15:37 UTC, nabil-brn commented on static/i18n/en/app.json
> +      "title": "Sorry, it looks like your device was disconnected",
Present perfect is more appropriate in that case imo, correct me if I'm wrong @dasilvarosa.
`was` -> `has been`

2021-03-21 15:37 UTC, nabil-brn commented on static/i18n/en/app.json
> +      "title": "Sorry, it looks like your device was disconnected",
`was` -> `has been`

2021-03-22 08:49 UTC, dasilvarosa approved these changes

2021-03-22 13:35 UTC, nabil-brn approved these changes

2021-03-22 13:50 UTC, merged