LL-5164 (Manager): app icons updated
LedgerHQ/ledger-live-desktop pull request #3727
Opened 2021-04-09 13:14 UTC by LFBarreto

(Manager): app icons updated
### Type

UI Polish
### Context

[LL-5164]
### Parts of the app affected / Test plan

Manager > app icons should use our currency icons when available or fallback on manager remote icon url

2021-04-14 16:31 UTC, Arnaud97234 requested changes
In dark / dusk mode, currencies with a dark background are not displayed properly (For instance: Algorand, Stellar, Eos, Cosmos)
![image](https://user-images.githubusercontent.com/13007150/114746012-8daf8680-9d4f-11eb-8cdf-bedda1cacf38.png)

2021-04-15 09:58 UTC, Arnaud97234 approved these changes

2021-04-15 15:18 UTC, valpinkman approved these changes

2021-04-15 15:19 UTC, valpinkman commented
needs rebase but ready to merge

2021-04-19 15:03 UTC, merged