Ll 3504 select fees strategy
LedgerHQ/ledger-live-desktop pull request #3738
Opened 2021-04-13 16:15 UTC by henri-ly

It's the rework of the UI system for fees

### Type

UI Polish / Feature

### Context

Should wait for this PR to be finished first
https://github.com/LedgerHQ/ledger-live-common/pull/1137

### Parts of the app affected / Test plan

Send for BTC / ETH

2021-04-15 11:49 UTC, LFBarreto requested changes
some missing translations but over than that its good :+1:

2021-04-15 11:49 UTC, LFBarreto commented on src/renderer/components/SelectFeeStrategy.js
> +type onClickType = {
prefer using Pascal case on type definitions

2021-04-15 11:49 UTC, LFBarreto commented on src/renderer/components/SelectFeeStrategy.js
> +                {label}
maybe put the label in i18n translation

2021-04-15 11:49 UTC, LFBarreto commented on src/renderer/components/SendFeeMode.js
> +          onClick={() => setAdvanceMode(!isAdvanceMode)}
you could put this callback in a useCallback since you're reusing it

2021-04-15 11:49 UTC, LFBarreto commented on src/renderer/families/bitcoin/FeesField.js
> +      <Label style={{ width: "200px" }}>Fees amount</Label>
translation here

2021-04-21 10:41 UTC, gre commented
@henri-ly you can bump directly live-common from this PR 👍

2021-04-27 14:12 UTC, gre requested changes

2021-04-27 14:12 UTC, gre commented on src/renderer/families/bitcoin/SendAmountFields.js
> +      onChange(bridge.updateTransaction(transaction, { feePerByte: amount, feesStrategy }));
we should not use bridge.updateTransaction anymore, instead `updateTransaction` should be used in order to not create race-condition issues.

2021-04-27 14:12 UTC, gre commented on src/renderer/families/ethereum/GasPriceField.js
> +      onChange(bridge.updateTransaction(transaction, { gasPrice, feesStrategy: "advanced" }));
same. i know it's old pattern but updateTransaction should be used (if we pass it as props)

2021-04-27 14:12 UTC, gre commented on src/renderer/families/ethereum/GasLimitField.js
> +      onChange(bridge.updateTransaction(transaction, { userGasLimit, feesStrategy: "advanced" }));
same. i know it's old pattern but updateTransaction should be used (if we pass it as props)

2021-04-27 14:12 UTC, gre commented on src/renderer/families/ethereum/SendAmountFields.js
> +      onChange(bridge.updateTransaction(transaction, { gasPrice: amount, feesStrategy }));
same.

2021-04-27 14:19 UTC, gre commented
someone in team will takeover this work to migrate some of the `onChange` usage back into a `updateTransaction(updater)` style. because the onChange usage today is creating sneaky problem in our app when you go typing too fast or changing things fast, it can create race condition and it's the source of a few reported problems.

2021-04-28 12:43 UTC, LFBarreto commented
closing this for #3782

2021-04-28 12:43 UTC, closed without merging