LL-5305 - add currencyName in Send and Receive flow
LedgerHQ/ledger-live-desktop pull request #3772
Opened 2021-04-26 16:08 UTC by valpinkman

As for addAccounts, adds currencyName into tracking event in Send and Receive flow

### Type

Improvement

### Context

LL-5305

### Parts of the app affected / Test plan

Analytics

2021-04-27 14:41 UTC, gre requested changes

2021-04-27 14:41 UTC, gre commented on src/renderer/modals/Receive/Body.js
> +  }, [account]);
this shouldn't be an effect to me.

2021-05-10 16:00 UTC, Arnaud97234 approved these changes, later dismissed
Event present on both Receive and Send flows.
No event on staking operations.
✅

2021-05-12 12:37 UTC, valpinkman commented on src/renderer/modals/Receive/Body.js
> +  }, [account]);
fixed

2021-05-12 16:25 UTC, juan-cortes submitted a review, later dismissed
lgtm

2021-05-18 11:03 UTC, Arnaud97234 requested changes
![image](https://user-images.githubusercontent.com/13007150/118640508-595d3900-b7d9-11eb-8f47-eb12d7b6ffe8.png)

In Send / Receive flows currencyName should be the token name instead of the parent Currency name.

2021-05-18 12:21 UTC, Arnaud97234 approved these changes
Ok for Currency as well as tokens.
✅

2021-05-18 16:29 UTC, JunichiSugiura approved these changes

2021-05-19 15:54 UTC, merged