[LL-4653] Redirect outdated app to CTA manager
LedgerHQ/ledger-live-desktop pull request #3778
Opened 2021-04-27 14:58 UTC by LFBarreto

[LL-4653] Redirect outdated app to CTA manager
### Type

UI Polish
### Context

[LL-4653]
### Parts of the app affected / Test plan

2021-04-27 14:59 UTC, LFBarreto commented
copy of #3643 without conflicts

2021-04-28 14:39 UTC, JunichiSugiura approved these changes, later dismissed
LGTM

2021-04-28 14:39 UTC, JunichiSugiura commented on src/renderer/components/DeviceAction/rendering.js
> +          {supportLink ? (
`supportLink && <Component />` would be enough.

2021-04-28 20:27 UTC, Arnaud97234 commented
@LFBarreto The CTA that should redirect to the manager is missing.
Use case:
- Polkadot app is outdated (You can find the NanoX version on provider 4)
- In the add account flow, when opening Polkadot app you see the outdated app Modal.
- On this modal there is no CTA redirecting to the Manager

2021-04-30 15:29 UTC, gre requested changes

2021-04-30 15:29 UTC, gre commented on src/renderer/components/DeviceAction/index.js
> +      error.name === "UpdateYourApp"
it should be `error instanceof UpdateYourApp` like done for others 🤔

2021-05-05 14:47 UTC, machard approved these changes

2021-05-10 14:16 UTC, Arnaud97234 approved these changes, later dismissed
If manager app update is mandatory then user see an error modal with a CTA that redirect to the manager.

2021-05-10 14:25 UTC, machard commented
@Arnaud97234 I can not push on @LFBarreto branch

2021-05-27 17:27 UTC, gre commented
@LFBarreto unclear status on this one.

2021-06-14 16:35 UTC, gre approved these changes

2021-06-14 16:36 UTC, gre commented
@Arnaud97234 the two last commit of @LFBarreto to me require a new QA on this. Even tho you did accept it, there are changes that I think invalidate your review. I let you both work on this. thanks.

2021-06-18 18:13 UTC, ychen-ledger approved these changes
Validated with: 
- Polkadot (DOT) Version 5.23.0
- FW version :1.2.4-6
- Manger provider 4
- Portfolio, Accounts, Send and Receive

2021-06-19 12:20 UTC, merged