[LL-3809] add tooltip to transaction device fields
LedgerHQ/ledger-live-desktop pull request #3779
Opened 2021-04-27 15:05 UTC by LFBarreto

- [LL-3809] add tooltip to transaction device fields
- [LL-3809] Add translation args for device confirm

### Type

Feature
### Context

[LL-3809]
### Parts of the app affected / Test plan

Lend for withdraw asset, I wasn't able to test it because eth fees cost too much :/

2021-04-27 15:06 UTC, LFBarreto commented
copy of #3696

2021-04-29 09:01 UTC, machard approved these changes

2021-05-03 08:47 UTC, valpinkman approved these changes

2021-05-11 15:16 UTC, Arnaud97234 requested changes
@LFBarreto

### Bugs found
1) I can't change the the gasPrice, When I move it it goes back to the default value.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/13007150/117840396-67143b00-b27c-11eb-8a9f-88aa3963e77b.gif)

---
2) When I click in the gasLimit input the value switch to 21000 (default value for ETH tx)

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/13007150/117840511-86ab6380-b27c-11eb-9a90-ef3333a23e91.gif)

2021-05-11 16:48 UTC, Arnaud97234 approved these changes
@LFBarreto  The tooltip is not translated. If it's not an issue we can merge
✅

2021-05-18 13:02 UTC, merged