LL-3504 select fees strategy
LedgerHQ/ledger-live-desktop pull request #3782
Opened 2021-04-28 12:43 UTC by LFBarreto

- [LL-3594] wip: fee selection for eth
- [LL-3504] add select fee strat for btc
- [LL-3504] add translate label
- [LL-3504] clean code + add trans
- [LL-3504] change advanced mode to null
- bump live-common
- (SendAmountFields): fix onChange -> updateTransaction usage
It's the rework of the UI system for fees

### Type

UI Polish / Feature
### Context

[LL-3504]
### Parts of the app affected / Test plan

Send for BTC / ETH

2021-04-28 12:43 UTC, LFBarreto commented
copy with review of #3738

2021-04-29 08:50 UTC, machard approved these changes

2021-04-29 13:47 UTC, JunichiSugiura commented
Is this a right ticket?

> LL-3594 wip: fee selection for eth

2021-04-29 14:08 UTC, JunichiSugiura requested changes

2021-04-29 14:08 UTC, JunichiSugiura commented on src/renderer/components/SendFeeMode.js
> +export default withTranslation()(SendFeeMode);
Could you avoid HOC when you can? useTranslate instead.

2021-04-29 14:08 UTC, JunichiSugiura commented on src/renderer/components/SendFeeMode.js
> +export default withTranslation()(SendFeeMode);
But you don't even need it this time because Trans is used here.

2021-04-29 15:44 UTC, gre commented
btw it's already part of live-common bump, so if we have to do changes, let's not forget to backreport them, but only if the changes are important to not invalidate ongoing QA.

2021-04-30 15:38 UTC, gre commented
included in #3773

2021-04-30 15:38 UTC, closed without merging