Prepare 2.27.0
LedgerHQ/ledger-live-desktop pull request #3799
Opened 2021-05-03 14:57 UTC by gre

2021-05-03 17:01 UTC, JunichiSugiura requested changes
I was gonna scanning through this pr since these codes are already reviewed but i can't ignore this.

2021-05-03 17:03 UTC, JunichiSugiura commented on src/renderer/components/BalanceInfos/index.js
> +        {valueChange.percentage && valueChange.percentage && (
I mean this. I'm gonna push a fix shortly.

2021-05-04 07:54 UTC, JunichiSugiura commented
Did we change the mock data for DAI countervalue? I'm wondering why the price not shown in asset allocation list.

2021-05-04 10:42 UTC, JunichiSugiura approved these changes

2021-05-04 17:57 UTC, gre commented
WTF

2021-05-06 07:20 UTC, merged