LL-5422 (Announcements): add device firmware + platform filtering
LedgerHQ/ledger-live-desktop pull request #3839
Opened 2021-05-17 15:46 UTC by LFBarreto

(Announcements): add device firmware + platform filtering
-> needs live-common bump
### Type

Feature
### Context

[LL-5422]
### Parts of the app affected / Test plan

Announcements + debug mock announcements

2021-05-19 14:05 UTC, valpinkman submitted a review, later dismissed

2021-07-27 07:55 UTC, gre requested changes
i don't see how the platform field can work here. **Was this tested?**

2021-07-27 07:55 UTC, gre commented on src/renderer/components/AnnouncementProviderWrapper.js
> +    platform: process.platform,
process.platform is one of 'aix', 'darwin', 'freebsd', 'linux', 'openbsd', 'sunos', 'win32' ( https://nodejs.org/api/process.html#process_process_platform )

which is not what you seem to expect at
https://github.com/LedgerHQ/ledger-live-common/blob/84d9acd711476c0ab95294f29918ad22bc87468c/src/notifications/AnnouncementProvider/logic.js#L22

2021-08-27 09:29 UTC, jgiamporcaro-ledger submitted a review, later dismissed

2021-08-27 13:15 UTC, ghost requested changes

2021-08-27 13:20 UTC, Arnaud97234 submitted a review, later dismissed
Tested on Mac, Linux and Windows.
✅

2021-08-31 17:10 UTC, Arnaud97234 submitted a review, later dismissed

2021-09-01 09:48 UTC, valpinkman approved these changes, later dismissed

2021-09-02 10:05 UTC, nabil-brn approved these changes
Testing done by Arnaud.

2021-09-02 10:06 UTC, merged