LL-5497 Grammar fix
LedgerHQ/ledger-live-desktop pull request #3862
Opened 2021-05-28 07:31 UTC by MortalKastor

Grammar fix

### Context

#3794 
https://ledgerhq.atlassian.net/browse/LL-5497

### Parts of the app affected

Wording in _Lend_ feature, when there's no matching account

2021-05-28 12:08 UTC, haammar-ledger commented
Nitpicking here, but this won't fit some currencies starting with a vowel... eg. "_you don't have a ALGO account_"

2021-05-31 10:19 UTC, valpinkman approved these changes

2021-06-03 08:31 UTC, juan-cortes requested changes
I'm going to be a pita but what happens when you don't have ETH, or ATOM, or Algorand?
That's also wrong grammar. We can't just say "You don't have a Algorand account." 
Maybe "You don't have any Algorand account**s**" would work best

2021-06-15 07:38 UTC, gre commented
for now we merge to be 1:1 with mobile. but plz raise to product initial task owner @juan-cortes

2021-06-15 07:38 UTC, merged