LL-5803 (Tron): fix issue with freshly created accounts page
LedgerHQ/ledger-live-desktop pull request #3878
Opened 2021-06-02 12:55 UTC by LFBarreto

(Tron): fix issue with freshly created accounts page
### Type

Bug Fix
### Context

[LL-5803]
### Parts of the app affected / Test plan

Create a new tron account.
-> go to its account page
-> should no longer crash

2021-06-03 08:21 UTC, juan-cortes submitted a review, later dismissed

2021-06-14 13:32 UTC, valpinkman approved these changes

2021-06-14 18:25 UTC, Arnaud97234 approved these changes
QA OK.
✅

2021-06-14 21:55 UTC, gre commented
@LFBarreto CI fails on linting.

@juan-cortes @valpinkman please be more careful on review to check ci says ✔️

2021-06-14 21:55 UTC, gre requested changes
fix flow/lint

2021-06-15 11:08 UTC, merged