LL-6017 (ServiceStatusProvider): use new filtered incidents hooks
LedgerHQ/ledger-live-desktop pull request #3915
Opened 2021-06-16 09:10 UTC by LFBarreto

(ServiceStatusProvider): use new filtered incidents hooks

### Type

Feature
### Context

[LL-6017]
### Parts of the app affected / Test plan

Service status drawer should filter out incidents that don't concern the users currencies
adding accounts should still show the issue as a currency down alert

2021-08-27 14:06 UTC, achabrolin-ledger submitted a review, later dismissed

2021-08-31 15:02 UTC, ychen-ledger requested changes
Hi @LFBarreto, everything is works very well for Bitcoin but please find below we have two issues with other coins(possibly is go into as one issue): 

1. In the step Crypto asset, when other coins is selected, we still have BTC incidents, please find the result as the video below:

https://user-images.githubusercontent.com/85551245/131526134-983746d6-b6ae-4c9b-be25-0088e56bfbce.mov

2. In the step Crypto asset, when we first select the BTC and then change to another coin, the page is not dynamic refresh with new coins, please find the result as the video below: 

https://user-images.githubusercontent.com/85551245/131526846-cc682fc3-d11a-4d88-9d9a-0ae4c08cc01b.mov

2021-09-06 15:12 UTC, ychen-ledger requested changes
Hey @LFBarreto, please find below: 

- The incident filter works well in status tab for added account, but seems broken in the Add accounts flow in the step Crypto asset, no announcement about selected currency😔, please see the result as the video below: 

https://user-images.githubusercontent.com/85551245/132228323-a7221276-7cee-493d-91af-b135c017739c.mov

- Just a confirm, only ETH and BTC have compatible mocked announcement, all the rest currency only have an mocked announcement as `Generic status error`, is it a limitation about MOCK, or there is an issue for filter, please check the result as below(checked with Cosmos, tezos, Bsc):
<img width="1026" alt="Screenshot 2021-09-06 at 15 40 50" src="https://user-images.githubusercontent.com/85551245/132228834-6f77e46d-eb64-4ca1-8a89-829c223a3742.png">

2021-09-07 10:04 UTC, ychen-ledger approved these changes
Validated with: 

- MacOS big Sur version 11.4
- LLD 2.32.2
- ETH/BTC/ATOM/XRP

2021-09-16 07:47 UTC, gre approved these changes

2021-09-16 07:47 UTC, merged