LL-4147 fix(accounts): make account row fully clickable
LedgerHQ/ledger-live-desktop pull request #3970
Opened 2021-07-08 15:49 UTC by jgiamporcaro-ledger

Account list padding was not clickable. From now the row will be fully clickable, padding included.

https://user-images.githubusercontent.com/33158502/124952643-b5dc1800-e014-11eb-82ca-41ef1da0bc08.mov

### Type

Fix

### Context

[LL-4147]

### Parts of the app affected / Test plan

Rows from the account list.

2021-07-09 07:36 UTC, LFBarreto submitted a review, later dismissed
could you test if the right click context menu is still working properly with those changes? :+1:

2021-07-09 08:56 UTC, juan-cortes commented
> could you test if the right click context menu is still working properly with those changes? 👍

I think you're right, if the left click was impacted, the right click is impacted too, probably move the `AccountContextMenu` up one level or something along those lines.

2021-07-09 12:34 UTC, jgiamporcaro-ledger commented
NIce catch mates, thanks!

I moved up the `AccountContextMenu` component and fixed up the change to my initial [commit](https://github.com/LedgerHQ/ledger-live-desktop/pull/3970/commits/5833b8ad9ab6681504caa04b1754f873aa9f9d49)

https://user-images.githubusercontent.com/33158502/125078418-a61b0d00-e0c2-11eb-948e-83e0c0899c22.mov

2021-07-13 07:38 UTC, LFBarreto approved these changes
:+1:

2021-07-15 15:38 UTC, nabil-brn requested changes
Unfortunately _left-click_ is no more working on sub accounts, I'm redirected to the parent account.

---
2.30.0-sha.5833b8ad9ab6681504caa04b1754f873aa9f9d49-win.exe.zip

2021-07-16 08:24 UTC, jgiamporcaro-ledger commented
Yeah, my bad, I didn't have ETH tokens so subAccounts wasn't listed when I fix the bug.
Thanks for sending me some tokens yesterday, I'll take a look on this one today 🦾

2021-07-16 13:46 UTC, jgiamporcaro-ledger commented
@nabil-brn 

Fixed 🔥 

https://user-images.githubusercontent.com/33158502/125957878-6f78b40a-49fb-442d-81eb-77e1211a71fa.mov

2021-07-16 13:49 UTC, jgiamporcaro-ledger commented on src/renderer/screens/accounts/AccountRowItem/index.js
> +  height: calc(100% + 20px);
These lines stick the vertical line to content title.

2021-07-20 12:50 UTC, nabil-brn approved these changes
:heavy_check_mark:  QA-ed

---
ledger-live-desktop-2.31.0-sha.a2a9b289642db9ceb38be7acd20195acd6bccd96-linux-x86_64.AppImage

2021-07-20 13:40 UTC, merged