Live common TypeScript with electron 13
LedgerHQ/ledger-live-desktop pull request #4072
Opened 2021-08-05 10:37 UTC by gre

this includes both work of TypeScript of Live-common and necessary upgrade of many libraries, including Electron 13.

2021-08-05 14:59 UTC, gre commented
CI come on.

2021-08-10 14:12 UTC, nabil-brn submitted a review, later dismissed

2021-08-11 14:04 UTC, nabil-brn requested changes
**Settings**
❌ Clear cache
`Uncaught (in promise) TypeError: Cannot read property 'getPath' of undefined at resolveUserDataDirectory (resolveUserDataDirectory.js?097f:20)`
❌ View user data
`Uncaught TypeError: Cannot read property 'getPath' of undefined at resolveUserDataDirectory (resolveUserDataDirectory.js?097f:20)`
❌ Reset Ledgerlive
`"TypeError: Cannot read property 'getPath' of undefined at resolveUserDataDirectory (webpack-internal:///./src/helpers/resolveUserDataDirectory.js:2:6888)
`✔️ Password lock
**Generic**
✔️ Deeplinks/External links
✔️ Export features (logs, operation history, swap operations)
✔️ language/theme settings (system option)
**System**
✔️ PID after closing the app / no zombies
✔️ USB
**Features**
✔️ WalletConnect
❌ Window interaction/iframes (Platform, Buy/Sell)
❌ Platform apps are not loading (Paraswap, Rainbow, etc.)
❌ _Select account_ button on Wyre app doesn't display any modal

---
Windows
2ff825f

2021-08-17 15:59 UTC, nabil-brn approved these changes
:heavy_check_mark: Tested on all platforms, no bugs found.

---
1c81656fb (HEAD -> live-common-ts-electron-12, ledger/live-common-ts-electron-12) snapshot

2021-08-17 16:28 UTC, merged