[LL-6803] generalize sign transaction workflow for all crypto
LedgerHQ/ledger-live-desktop pull request #4112
Opened 2021-08-18 10:33 UTC by achabrolin-ledger

Leverage and update the current sign transaction workflow in order to make it more generalized and work with all cryptos

This also allows to skip fees step if already provided by the dapp in the related platform transaction.

<details>
<summary>Demo 🎥 </summary>

https://user-images.githubusercontent.com/87011321/129882949-438fb79f-ec16-4e7f-a671-87611fa5a101.mp4

</details>

### Type

Feature

### Context

https://ledgerhq.atlassian.net/browse/LL-6803

### Parts of the app affected / Test plan

Sign transaction flow in app platform context.

To test: **TODO**

2021-08-18 12:35 UTC, achabrolin-ledger commented on src/renderer/modals/SignTransaction/steps/StepSummary.js
> +// @flow
This component has been duplicated 1 to 1 from the send workflow as of today.
When we will rework the design of the sign transaction flow, we will be able to tailor it accordingly.

2021-08-18 12:41 UTC, achabrolin-ledger commented on src/renderer/modals/SignTransaction/Body.js
> +          label: <Trans i18nKey="send.steps.amount.title" />,
The label could be changed to "Fees" instead of "Amount" as of today

2021-08-27 08:06 UTC, LFBarreto submitted a review, later dismissed

2021-08-30 15:12 UTC, lruggiero-ledger requested changes
QA KO - Check comments at https://ledgerhq.atlassian.net/browse/LL-6803?focusedCommentId=126381

2021-08-30 16:19 UTC, achabrolin-ledger commented
> QA KO - Check comments at https://ledgerhq.atlassian.net/browse/LL-6803?focusedCommentId=126381

@lruggiero-ledger Should be fixed here f6a40557eaa19947bdb278552ef3388f0143f725

I added the error message to the summary screen but couldn't reproduce the your experienced behaviour

2021-08-31 12:51 UTC, machard commented
this is used by wallet connect sign transaction flow as well. just QA check maybe. otherwise looks ok

2021-08-31 16:09 UTC, LFBarreto approved these changes

2021-08-31 16:44 UTC, IAmMorrow approved these changes

2021-09-01 10:22 UTC, merged