LL-7450 Fix regression in asset distribution bars
LedgerHQ/ledger-live-desktop pull request #4270
Opened 2021-09-27 13:55 UTC by juan-cortes

## 🦒 Context (issues, jira)
https://ledgerhq.atlassian.net/browse/LL-7450

## 💻  Description / Demo (image or video)
While fixing https://ledgerhq.atlassian.net/browse/LL-6579 we (I) introduced a regression in the percentage bars for distributions. By localizing the value we turned floating numbers into strings, and broke the css that determined how much _bar_ to draw colored in languages that don't use a period for the decimal point (like French). This fixes that.

It was not detected by Spectron testing since we disable the bars due to pixel discrepancies, perhaps we should try something else instead of just disabling them.

<img width="1398" alt="Screenshot 2021-09-27 at 15 47 58" src="https://user-images.githubusercontent.com/4631227/134922239-9240c7c9-f8ed-4360-9e0d-8da4699c356c.png">

## 🖤  Expectations to reach

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [x] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [x] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [ ] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

2021-09-28 08:43 UTC, valpinkman submitted a review, later dismissed

2021-09-29 08:54 UTC, LFBarreto requested changes

2021-09-29 08:54 UTC, LFBarreto commented on src/renderer/components/AssetDistribution/index.js
> +    console.log("wadus", { list });
remove this :grin:

2021-09-29 09:03 UTC, LFBarreto approved these changes

2021-10-04 09:23 UTC, Arnaud97234 approved these changes

2021-11-04 13:25 UTC, achabrolin-ledger approved these changes

2021-11-16 08:42 UTC, merged