LL-7481 - Change learn more css in manager app list
LedgerHQ/ledger-live-desktop pull request #4358
Opened 2021-10-27 18:11 UTC by nparigi-ledger

## 🦒 Context (issues, jira)

[LL-7481]

## 💻  Description / 

Demo (image or video)

https://user-images.githubusercontent.com/89014981/139122615-e9704155-cc17-48ef-9412-f113984a917e.mp4

## 🖤  Expectations to reach

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [x] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

[LL-7356]: https://ledgerhq.atlassian.net/browse/LL-7356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LL-7481]: https://ledgerhq.atlassian.net/browse/LL-7481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2021-10-29 14:39 UTC, LFBarreto submitted a review, later dismissed

2021-10-29 16:13 UTC, ychen-ledger requested changes
@nparigi-ledger It seems CI failed of snapshots, could you please do an update?

2021-12-02 19:59 UTC, ychen-ledger approved these changes
Validated as the first comment in jira, all rest improvement will be done in the https://ledgerhq.atlassian.net/browse/LL-8538

2021-12-20 08:46 UTC, LFBarreto approved these changes

2021-12-21 08:49 UTC, merged