add subAccount playwright
LedgerHQ/ledger-live-desktop pull request #4501
Opened 2021-12-03 16:06 UTC by aulric-ledger

## 🦒 Context (issues, jira)
Playwright - UI test
Add Accounts flow -> token account

## 💻  Description / Demo (image or video)

- Migrate add sub account test from spectron.
- Receive modal page object
- AccountsPage page object

## 🖤  Expectations to reach

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [ ] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

2021-12-06 17:19 UTC, valpinkman commented
/generate-screenshots

2021-12-06 17:22 UTC, valpinkman submitted a review, later dismissed

2021-12-07 09:29 UTC, valpinkman commented
/generate-screenshots

2021-12-07 10:16 UTC, valpinkman submitted a review, later dismissed

2021-12-07 14:20 UTC, nabil-brn requested changes
Recommendations:

- Some indent issues
- Test is a bit flaky, after 4 executions, it failed once
- Please check the screenshots that have been taken (e.g. loading steps are not relevant)
- Split tests as much as you can by features/flow etc. (e.g. you can create a `receive.spec.ts` test file)

2021-12-07 14:21 UTC, nabil-brn commented on src/renderer/modals/Receive/steps/StepReceiveFunds.js
> +                <Button data-test-id={"receive-receive-continue-button"} primary onClick={onClose}>
Is there a reason why the id starts with "receive-receive-..." ?

2021-12-07 17:58 UTC, aulric-ledger commented
/generate-screenshots

2021-12-22 09:29 UTC, nabil-brn commented
/generate-screenshots

2021-12-22 09:56 UTC, nabil-brn commented
/generate-screenshots

2021-12-22 16:34 UTC, nabil-brn commented
/generate-screenshots

2021-12-22 18:33 UTC, nabil-brn commented
/generate-screenshots

2021-12-23 08:49 UTC, nabil-brn approved these changes, later dismissed

2021-12-23 09:32 UTC, valpinkman approved these changes

2021-12-23 10:31 UTC, merged