LL-MKT
LedgerHQ/ledger-live-desktop pull request #4502
Opened 2021-12-05 22:29 UTC by LFBarreto

## 🦒 Context (issues, jira)
LL-MKT (MKT): init v3 provider

## 💻  Description / Demo (image or video)

## 🖤  Expectations to reach

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [ ] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

2022-01-04 15:31 UTC, LFBarreto commented
/generate-screenshots

2022-01-05 09:32 UTC, LFBarreto commented
/generate-screenshots

2022-01-05 11:07 UTC, valpinkman commented
Reviewed the code and tested locally. The feature seems to be ready and pretty bug free (I have testes the happy paths... I'm  sure we can stress test it a bit more)

Code wise, it's kind of a pain to test because the builds hide the marketpage in sidebar (I cannot wait to have feature flags)

Other than that, looks good to me

https://user-images.githubusercontent.com/671786/148207987-884cf452-871f-402f-9e03-03cea6f6b0f7.mp4

2022-01-05 11:08 UTC, valpinkman requested changes, later dismissed
Removing console.log and it will be ready for me

2022-01-05 11:08 UTC, valpinkman commented on src/renderer/screens/platform/Catalog.js
> +  console.log(manifests);
remove console.log

2022-01-05 11:45 UTC, achabrolin-ledger submitted a review, later dismissed

2022-01-05 13:04 UTC, valpinkman approved these changes, later dismissed

2022-01-05 16:00 UTC, LFBarreto commented
/generate-screenshots

2022-01-05 17:02 UTC, ofreyssinet-ledger approved these changes

2022-01-05 17:03 UTC, merged