LL-8694 Fix token-id display
LedgerHQ/ledger-live-desktop pull request #4632
Opened 2022-01-12 15:06 UTC by grsoares21

## 🦒 Context (issues, jira)
[LL-8694] - see QA comments

The issue was happening because we were assuming that any copiable field would be addresses and we were using a specific component for hash adresses inside the copiable field component. The PR makes the Copiable field component generic for any children and moves the logic for addresses up in the tree.

## 💻  Description / Demo (image or video)
![fix-token-id-display](https://user-images.githubusercontent.com/6013294/149166182-02305bf6-d90b-411b-8768-9725c7ef670a.gif)

## 🖤  Expectations to reach

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [x] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [x] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

2022-01-26 09:59 UTC, lambertkevin approved these changes

2022-01-26 16:02 UTC, ychen-ledger requested changes
The feature for really long token ID (displayed number …number )is broken in the PR, please see more detail in jira comment

2022-01-27 14:42 UTC, valpinkman requested changes

2022-01-27 14:48 UTC, valpinkman approved these changes

2022-01-27 15:54 UTC, merged

2022-01-31 17:11 UTC, ychen-ledger reviewed
Validated with MacOS-  LLD Ledger Live 2.37.2-sha.0c389b63a5fa5988a1bceced30f765bd32a6add4