Bump ledgerhq deps
LedgerHQ/ledger-live-desktop pull request #4653
Opened 2022-01-18 13:33 UTC by chabroA

## 🦒 Context (issues, jira)
Update following deps:

- `@ledgerhq/hw-transport-node-hid-singleton`: `"6.20.0"` -> `"6.23.0"`
- `@ledgerhq/live-common`: `"^21.26.1"` -> `"^21.27.0"`

## 💻  Description / Demo (image or video)

## 🖤  Expectations to reach

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [x] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [x] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [x] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

2022-01-18 14:00 UTC, juan-cortes commented
This includes the work from https://github.com/LedgerHQ/ledger-live-desktop/pull/4647 which is currently in QA by @alalmi-ledger so merging this should be done only after it's qa ok over there. 

Closes https://github.com/LedgerHQ/ledger-live-desktop/pull/4647

2022-01-19 13:48 UTC, juan-cortes commented
QA seem to have found some issues with a specific device, we need more investigation on the cause

2022-01-19 14:58 UTC, juan-cortes commented
Reverting the changes on the singleton transport until we figure out what's causing the erratic connection QA found. Can't afford introducing a bug like this that would impact many users. So, we need https://github.com/LedgerHQ/ledgerjs/pull/770 merged, ledgerjs released with that, and to use the new version here again.

Or in the meantime, drop the singleton library bump if you need the rest.

2022-01-19 14:59 UTC, juan-cortes requested changes

2022-01-19 14:59 UTC, juan-cortes commented on package.json
> +    "@ledgerhq/live-common": "^21.27.0",
QA KO makes this not possible

2022-01-20 10:23 UTC, chabroA commented
> Reverting the changes on the singleton transport until we figure out what's causing the erratic connection QA found. Can't afford introducing a bug like this that would impact many users. So, we need [LedgerHQ/ledgerjs#770](https://github.com/LedgerHQ/ledgerjs/pull/770) merged, ledgerjs released with that, and to use the new version here again.
> 
> Or in the meantime, drop the singleton library bump if you need the rest.

@juan-cortes Ok so if I understand correctly we can bump `@ledgerhq/live-common: "^21.26.1" -> "^21.27.0"` but not `@ledgerhq/hw-transport-node-hid-singleton`?
If that the case, that's fine by me 👌

2022-01-20 13:56 UTC, chabroA commented
Duplicated by https://github.com/LedgerHQ/ledger-live-desktop/pull/4664

2022-01-20 13:56 UTC, closed without merging