LIVE-448 - Add playwright test suite for market page
LedgerHQ/ledger-live-desktop pull request #4736
Opened 2022-02-11 16:17 UTC by thomasrogerlux

## 🦒 Context (issues, jira)

[LIVE-448]

## 💻  Description / Demo (image or video)

Add test suite for market page (previous PR https://github.com/LedgerHQ/ledger-live-desktop/pull/4704 got closed by release)

## 🖤  Expectations to reach

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [x] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [x] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [ ] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

PR must pass CI, merge develop if conflicts, do not force push. Thanks!

2022-02-21 15:46 UTC, thomasrogerlux commented
/generate-screenshots

2022-02-22 09:16 UTC, thomasrogerlux commented
Wait for https://github.com/LedgerHQ/ledger-live-common/pull/1728

2022-02-24 10:21 UTC, thomasrogerlux commented
/generate-screenshots

2022-02-24 10:45 UTC, thomasrogerlux commented
/generate-screenshots

2022-02-27 14:19 UTC, LFBarreto requested changes
just update the llc version and were good :+1:

2022-02-27 14:19 UTC, LFBarreto commented on package.json
> +    "@ledgerhq/live-common": "https://github.com/LedgerHQ/ledger-live-common.git#develop",
could you update this :pleading_face:

2022-02-28 11:07 UTC, LFBarreto approved these changes

2022-02-28 12:26 UTC, thomasrogerlux commented
/generate-screenshots

2022-02-28 17:29 UTC, thomasrogerlux commented
/generate-screenshots

2022-03-01 09:15 UTC, thomasrogerlux commented
/generate-screenshots

2022-03-02 08:50 UTC, thomasrogerlux commented
/generate-screenshots

2022-03-03 14:26 UTC, thomasrogerlux commented
generate-screenshots

2022-03-03 14:26 UTC, thomasrogerlux commented
/generate-screenshots

2022-03-07 02:40 UTC, nabil-brn commented
/generate-screenshots

2022-03-07 09:25 UTC, nabil-brn commented
/generate-screenshots

2022-03-07 09:56 UTC, nabil-brn approved these changes
Good to go, no new screenshots, the tests should not be flaky anymore once we merged this PR.

2022-03-07 10:31 UTC, valpinkman requested changes
Except for the splitting of the one test I mentionned, everything looks fine to me. Fix this and we will be ready ;)

2022-03-07 10:31 UTC, valpinkman commented on tests/specs/market.spec.ts
> +    expect(await page.screenshot()).toMatchSnapshot("market-page.png");
only one expect per test 🙏🏻

2022-03-07 10:41 UTC, thomasrogerlux commented on tests/specs/market.spec.ts
> +    expect(await page.screenshot()).toMatchSnapshot("market-page.png");
Done!

2022-03-07 10:51 UTC, valpinkman approved these changes

2022-03-07 13:39 UTC, nabil-brn approved these changes

2022-03-07 14:09 UTC, merged