Add Playwright tests for feature flags and the new Learn page
LedgerHQ/ledger-live-desktop pull request #4751
Opened 2022-02-16 18:05 UTC by thomasrogerlux

## 🦒 Context (issues, jira)

https://github.com/LedgerHQ/ledger-live-desktop/pull/4717 is introducing a new Learn section in the app. This PR add tests to it and ensure it's correctly feature flagged

## 💻  Description / Demo (image or video)

This PR do three things:
- Setup Playwright to override RemoteConfig when needed
- Test the Learn page (basic testing for now)
- Test the feature flagging of the learn page

## 🖤  Expectations to reach

PR must pass CI, rebase develop if conflicts. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [x] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [x] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [ ] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

2022-02-17 09:20 UTC, LFBarreto requested changes
변경 요청 :+1:

2022-02-17 09:20 UTC, LFBarreto commented on src/renderer/components/FirebaseFeatureFlags.tsx
> +    const feature: Feature = JSON.parse(jsonValue);
try catch desune?

2022-02-28 11:03 UTC, LFBarreto approved these changes

2022-03-08 08:29 UTC, closed without merging

2022-03-08 08:30 UTC, thomasrogerlux commented
Closed because maintaining feature flag related tests won't make sense when we start having a lot of them

The learn page will be tested in another PR