bugfix/LIVE 1356
LedgerHQ/ledger-live-desktop pull request #4826
Opened 2022-03-09 11:31 UTC by tlaforge-ledger

## 🦒 Context (issues, jira)

[LIVE-1356]

## 💻  Description / Demo (image or video)

## 🖤  Expectations to reach

PR must pass CI, rebase develop if conflicts. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked:
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [*] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

2022-03-09 11:38 UTC, tlaforge-ledger commented
HODL cause possible nano Blue images are coming.

2022-03-09 14:27 UTC, thomasrogerlux approved these changes
Code looks good to me! Maybe nano S shouldn't be default as it's getting replaced by S plus soon?

2022-03-11 10:47 UTC, juan-cortes requested changes
Just have to change the icon for blue dark, you used the light one, and we're good

2022-03-11 10:47 UTC, juan-cortes commented on src/renderer/screens/manager/Disconnected.js
> +    dark: blue,
Blue dark?

2022-03-11 10:54 UTC, juan-cortes approved these changes

2022-03-11 15:18 UTC, merged