LIVE-1653 - Fix experimental countervalues toggle
LedgerHQ/ledger-live-desktop pull request #4832
Opened 2022-03-11 11:24 UTC by ofreyssinet-ledger

**Bug description:** _"On LLD 2.38.3, customer’s experimental countervalues API toggle keep changing it’s status back to enabled after customer disabled it and moved to a different menu."_

Fixed 2 things:
- For `LEDGER_COUNTERVALUES_API`, the values of `valueOn` and `valueOff` in `src/renderer/experimental.js` were reversed (`valueOff` should be matching the `default` value declared in LLC's `env.ts` and `valueOn` should be the experimental value). This mismatch between the `default` value and the `valueOff` was causing the experimental switch toggle to have no effect.
- The state of the switch in `ExperimentalSwitch` now reflects the _real_ state of the experimental feature, it's not an internal state. This internal state was causing an issue where because of the previously described issue, clicking on the switch would switch the internal state, thus making it appear like the switch was having an effect, but actually nothing was happening in the background, only the switch's internal state was changing. Thus when leaving and coming back to the page, the switch was reverted back to it's initial state (it's "real" state).

## 🦒 Context (issues, jira)

[LIVE-1653]
[TECSUPPORT-1119]

## 💻  Description / Demo (image or video)

#### Before:

_(see video in ticket [TECSUPPORT-1119], can't share here for privacy reasons)_

The user goes to the "Experimental features" setting section.
He notices that "Experimental countervalues API" is on.
He toggles it "off", then goes to the "Help" section and comes back to "Experimental features" and sees that even though it was toggled "off", it's back "on".

#### After:

https://user-images.githubusercontent.com/91890529/157856151-f021598b-041c-4a10-9c59-b66e2292e6b4.mov

## 🖤  Expectations to reach

PR must pass CI, rebase develop if conflicts. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [x] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [x] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

2022-03-11 13:02 UTC, valpinkman approved these changes

2022-03-11 13:16 UTC, ofreyssinet-ledger commented
/generate-screenshots

2022-03-14 10:12 UTC, thomasrogerlux approved these changes

2022-04-28 12:03 UTC, ychen-ledger requested changes
@ofreyssinet-ledger Plz fix conflicts

2022-04-28 13:37 UTC, ychen-ledger approved these changes
Validated with: 
- LLD 2.40.2-sha.d635bc3642ec7668d5729372fe715c2d8680400d
- MacOS
- Value in console/UI navigation

2022-04-28 15:25 UTC, merged