Multibuy 1.5
LedgerHQ/ledger-live-desktop pull request #4834
Opened 2022-03-12 18:20 UTC by IAmMorrow

## 🦒 Context (issues, jira)

https://ledgerhq.atlassian.net/browse/LIVE-717

## 💻  Description / Demo (image or video)

This PR enable the MultiBuy 1.5 implementation including:
- New platform app providers
- Dynamic links to buy in accounts, market and asset pages
- Replaced buy section with Ramp catalog "multibuy" 

## 🖤  Expectations to reach

PR must pass CI, rebase develop if conflicts. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [ ] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

2022-03-12 21:23 UTC, IAmMorrow commented
/generate-screenshots

2022-03-13 13:50 UTC, IAmMorrow commented
/generate-screenshots

2022-03-14 08:24 UTC, LFBarreto requested changes
Meh :laughing: 
remove console log and do a quick lint pls :pray:

2022-03-14 08:24 UTC, LFBarreto commented on src/renderer/components/PerCurrencySelectAccount/state.js
> +    console.log({ availableAccounts });
:hankey:

2022-03-14 08:24 UTC, LFBarreto commented on src/renderer/screens/account/AccountHeaderActions.js
> +  console.log({
:hankey:

2022-03-14 08:24 UTC, LFBarreto commented on src/renderer/screens/exchange/Buy/index.js
> +  console.log({ sortedCurrencies });
:hankey:

2022-03-14 08:24 UTC, LFBarreto commented on src/renderer/screens/market/MarketCoinScreen/index.tsx
> +    console.log(onRampProviders, currency);
:hankey:

2022-03-14 08:24 UTC, LFBarreto commented on src/renderer/screens/platform/App.js
> +  console.log(appId, manifest);
:hankey:

2022-03-15 14:07 UTC, ggilchrist-ledger commented
/generate-screenshots

2022-03-15 14:19 UTC, gre requested changes
lint issue

2022-03-15 15:02 UTC, merged