feat(walletconnect): enable polygon
LedgerHQ/ledger-live-desktop pull request #4845
Opened 2022-03-16 16:02 UTC by qd-qd

This commit adds the walletconnect button to the polygon account page.

## 🦒 Context (issues, jira)

Wallet Connect is EVM-compatible, as we support Polygon now, it makes sense to enable this button on the Polygon account page.

## 💻  Description / Demo (image or video)

## 🖤  Expectations to reach

PR must pass CI, rebase develop if conflicts. Thanks!

- **on QA**: at least one of these two checkboxes must be checked:
  - [ ] a specific test planned is defined on Jira
  - [ ] this PR is covered by automatic UI test
- **on delivery**: at least one of these two checkboxes must be checked: 
  - [ ] Option 1: **no impact**: The changes of this PR have ZERO impact on the userland (invisible for users)
  - [ ] Option 2: **atomic delivery**: the changes is atomic and complete (no partial delivery)

2022-03-17 09:20 UTC, thomasrogerlux approved these changes

2022-03-17 09:55 UTC, qd-qd commented
/generate-screenshots

2022-03-17 11:11 UTC, LFBarreto requested changes, later dismissed
This PR will conflict with #4828
to be rebased after release and updated :+1:

2022-04-06 09:03 UTC, qd-qd commented
/generate-screenshots

2022-04-19 14:13 UTC, merged